In [1]:
import numpy as np

In [2]:
import pandas as pd

from sklearn.model_selection import train_test_split

In [3]:
from sklearn import svm

In [4]:
import matplotlib.pyplot as plt

In [6]:
letters_df = pd.read_csv("./data/letterdata.csv")

In [11]:
letters_df.head()

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10

In [16]:
X, y = np.array(letters_df)[:,1:], np.array(letters_df)[:,0]

In [21]:
clf = svm.SVC()

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.3, random_state=1)

In [29]:
clf.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [30]:
y_pred = clf.predict(X_test)

In [31]:
from  sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred)
print(score)

0.9671666666666666

In [32]:
pd.crosstab(y_test, y_pred)

col_0,A,B,C,D,E,F,G,H,I,J,...,Q,R,S,T,U,V,W,X,Y,Z
row_0,,,,,,,,,,,,,,,,,,,,,
A,232,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
B,0,236,0,0,1,0,0,0,0,0,...,0,1,1,0,0,1,0,2,0,0
C,0,0,223,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
D,0,1,0,227,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
E,0,1,0,0,209,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,2
F,0,0,0,0,2,211,0,0,1,0,...,0,0,0,1,0,1,0,0,0,0
G,0,1,2,1,0,0,220,0,0,0,...,0,0,0,0,0,1,2,0,0,0
H,0,1,0,6,0,0,1,215,0,0,...,0,5,0,0,1,0,0,0,0,0
I,0,0,0,0,0,0,0,0,191,6,...,0,0,0,0,0,0,0,1,0,0
J,0,0,0,0,0,0,0,1,10,188,...,0,0,0,0,0,0,0,0,0,0
K,0,0,0,0,0,0,0,1,0,0,...,0,4,0,0,0,0,0,4,0,0
L,0,1,1,0,2,0,0,3,0,0,...,0,0,0,0,0,0,0,3,0,0
M,0,3,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
N,0,0,0,3,0,0,0,2,0,0,...,0,4,0,0,0,2,0,0,0,0
O,0,0,1,4,0,0,0,0,0,0,...,3,0,0,0,1,0,1,0,0,0
P,0,1,0,0,1,12,0,1,0,0,...,1,0,0,0,0,0,1,0,1,0
Q,0,0,0,0,0,0,0,0,0,0,...,233,0,0,0,0,0,0,0,0,0
R,0,8,0,0,1,0,0,1,0,0,...,1,207,0,0,0,0,0,0,0,0
S,0,1,0,0,2,0,0,0,0,0,...,0,1,252,0,0,0,0,0,0,0
T,0,0,1,1,0,0,0,0,0,0,...,0,0,0,246,0,0,0,1,1,0
U,0,0,0,0,0,0,0,2,0,0,...,0,0,0,0,237,0,0,0,0,0
V,0,6,0,0,0,0,0,1,0,0,...,0,1,0,0,0,209,0,0,0,0
W,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,225,0,0,0
X,0,0,0,2,1,0,0,0,0,0,...,1,0,0,1,0,0,0,230,0,0
Y,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,2,0,0,0,253,0
Z,0,0,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,232